Feat: Modified ExtendedVersionAdminMixin to allow for the alteration of a field from cms_config
django-cms/djangocms-versioning pull request #275
Opened 2022-05-24 14:44 UTC by adam-murray

## Description
By adding extended_admin_field_modifiers to an apps cms_config, it is possible to provide a method, which can alter a field in the admin. The rationale for this is that injecting things like icons, or further information from other apps which use Versioning, can be done without monkeypatching, or forking versioning for oneself. 

To alter a field, add:
`extended_admin_field_modifiers = (model, field_name, method)`
With model being a model which is registered with an admin class that inherits ExtendedVersionAdminMixin
field_name being the name of the target field
method is a method which takes (obj, field) and returns the value to be displayed

## Related resources

* #...
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-05-26 13:06 UTC, Aiky30 requested changes
Some configuration changes and some cleanup required. Please reach out if you wan tto discuss anything.

2022-05-26 13:06 UTC, Aiky30 commented on djangocms_versioning/admin.py
> +        tuple_display = self.list_display
I can't see why list_display is not used when the contents is just reset to the original variable on line 303: https://github.com/django-cms/djangocms-versioning/pull/275/files#diff-c3366f60f43af1ae0a294533004f87015a920b766af7133ae5ac52c50ad86b29R304

2022-05-26 13:06 UTC, Aiky30 commented on djangocms_versioning/cms_config.py
> +            self.add_to_field_extension[model] = dict()
Supplying a dict as mentioned removes the need to do this because the extended_admin_field_modifiers will already be in this format.

2022-05-26 13:06 UTC, Aiky30 commented on djangocms_versioning/admin.py
> +        if modifier_dict:
There's a natural break in the code here to add this into a function after if modifier_dict.

2022-05-30 10:05 UTC, Bernardvdv approved these changes

2022-05-31 15:08 UTC, Aiky30 requested changes
Changes required to:
- Outdated documentation
- Test formatting and 1 test contents

2022-05-31 15:08 UTC, Aiky30 commented on tests/test_cms_config.py
> +    def test_field_extension_populates(self):
Missing docstring

2022-05-31 15:08 UTC, Aiky30 commented on tests/test_cms_config.py
> +    def test_field_extension_proper_error_non_iterable(self):
Missing docstring

2022-06-08 14:39 UTC, merged