feat: Add configuration to manage redirect on publish
django-cms/djangocms-versioning pull request #358
Opened 2023-10-30 12:44 UTC by fsbraun

## Description

Currently, upon publishing a page (or other content object) the user is redirected to the version admin of that object. This is excellent for power users.

This PR adds the setting `DJANGOCMS_VERSIONING_ON_PUBLISH_REDIRECT` with three possible values:

* `"published"`: Redirects to the objects `.get_absolute_url()` (if available, preview endpoint otherwise). This is close to v3's behaviour and potentially a good setting for an occasional editor.
* `"preview"`:  Redirects to the object's preview endpoint, just as most other user interactions.
* `"versions"`:  Redirects to the object's version list (as before)

The default is `"published"`.

This is a draft PR. Tests will work, once #357 is merged.

## Related resources

* #357 
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2023-11-19 16:10 UTC, fsbraun commented
@marksweb I've fixed the tests for this. For py3.12 they keep failing due to the django-app-helper dependency.

2023-11-22 22:36 UTC, marksweb requested changes

2023-11-23 06:09 UTC, fsbraun commented on tests/test_admin.py
> +        self.assertRedirectsToPrewview(response, poll_version)
I thought I had fixed this! 🤔

2023-12-28 10:35 UTC, marksweb approved these changes

2023-12-28 11:22 UTC, merged